onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider {top_mmcme4 Signals}
add wave -noupdate /top_tb/U1/SSTEP
add wave -noupdate /top_tb/U1/STATE
add wave -noupdate /top_tb/U1/RST
add wave -noupdate /top_tb/U1/CLKIN
add wave -noupdate /top_tb/U1/SRDY
add wave -noupdate /top_tb/U1/LOCKED_OUT
add wave -noupdate /top_tb/U1/CLK0OUT
add wave -noupdate /top_tb/U1/CLK1OUT
add wave -noupdate /top_tb/U1/CLK2OUT
add wave -noupdate /top_tb/U1/CLK3OUT
add wave -noupdate /top_tb/U1/CLK4OUT
add wave -noupdate /top_tb/U1/CLK5OUT
add wave -noupdate /top_tb/U1/CLK6OUT
add wave -noupdate -divider {ROM Contents}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[63]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[62]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[61]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[60]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[59]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[58]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[57]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[56]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[55]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[54]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[53]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[52]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[51]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[50]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[49]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[48]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[47]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[46]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[45]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[44]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[43]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[42]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[41]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[40]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[39]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[38]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[37]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[36]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[35]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[34]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[33]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[32]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[31]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[30]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[29]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[28]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[27]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[26]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[25]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[24]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[23]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[22]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[21]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[20]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[19]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[18]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[17]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[16]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[15]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[14]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[13]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[12]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[11]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[10]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[9]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[8]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[7]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[6]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[5]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[4]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[3]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[2]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[1]}
add wave -noupdate {/top_tb/U1/mmcm_drp_inst/rom[0]}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {972616 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 246
configure wave -valuecolwidth 109
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {971025 ps} {995275 ps}
